Default to IPv6 if host does not have IPv4
Otherwise on host with IPv6-only mgmt/corosync this will fail
with error:

{{ ansible_default_ipv4.address }}: 'dict object' has no attribute 'address'